dist: trusty
language: clojure
lein: 2.8.1
services:
  - redis-server
before_script:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
  - echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org
  - sleep 15 #mongo may not be responded directly. See http://docs.travis-ci.com/user/database-setup/#MongoDB
  - mongo --version
  - sudo service redis-server start --bind 127.0.0.1
script: lein midje
jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk9
services:
  - mongodb
